### PR TITLE
fixed 1.8.x ref. mismatch

### PR DESCRIPTION
**Pull request by brtnfld**
tested with 1.8.16, 1.8.21, 1.8.22, hdf5_1_8

### CODE REVIEW

**Comment by brtnfld** [comment]
@lrknox can you review this?

**Review by byrnHDF — COMMENTED** [review]
Will CMake need changes?

**Comment by brtnfld** [comment]
If CMake wants to work with the hdf5 version other than the latest releases of each, then yes cmake needs to be updated to check the correct reference files.

**Comment by byrnHDF** [comment]
Okay, I will update cmake after this is merged.

**Review by lrknox — APPROVED** [review]

**Pull request merged**
