### PR TITLE
added version check in test script

### PR DESCRIPTION
**Pull request by brtnfld**

### CODE REVIEW

**Comment by brtnfld** [comment]
For H5T, h5dump references for objref, and regref, are not right for 1.10 versions.
```
      DATA {
-         GROUP 1400 "/G1"
-            DATA {
-            }
-         DATASET 800 "/DS2"
-            DATA {
-            }
+      (0): GROUP 1400 /G1 , DATASET 800 /DS2 
       }
```


@byrnHDF do you know what version h5dump was changed?

**Comment by byrnHDF** [comment]
I'm pretty sure that h5dump output changed for 1.12 library. Which is why there is a 112 folder in the 110 testfiles dir. If you are using 1.12 h5dump with 1.10 API, then the library version determines the h5dump output.

**Review by byrnHDF — APPROVED** [review]

**Comment by brtnfld** [comment]
It looks like it changes between 1.10.6 and 1.10.7

**Comment by byrnHDF** [comment]
The type description does change because of unsupported types, but I thought the reference only changed in 1.12. But we may have decided to add the file name in 1.10.7.

**Review by lrknox — APPROVED** [review]

**Pull request merged**
