### PR TITLE
Fix read include file

### PR DESCRIPTION
**Pull request by byrnHDF**

### CODE REVIEW

**Review by brtnfld — APPROVED** [review]

**Review by brtnfld — COMMENTED** [review]
Actually, this only needs to be done if Fortran is enabled.

**Comment by byrnHDF** [comment]
Also nbit test is dependent on version; 1.8.22 has no precision - 1.8.23 has precision.
Probably the same with other branches.

**Comment by byrnHDF** [comment]
> Also nbit test is dependent on version; 1.8.22 has no precision - 1.8.23 has precision. Probably the same with other branches.
Not sure why C example passes and Fortran fails

**Review by brtnfld — COMMENTED** [review]
Where is the update to maketestref.sh.in used to generate these new files?

**Comment by byrnHDF** [comment]
> Where is the update to maketestref.sh.in used to generate these new files?

There will be more most likely because of changes to tools. May need to change that file and the names to depend on version used to create the files. Maybe a subdir instead of a xxx22.h5 name?

**Comment by brtnfld** [comment]
Do you plan on adding a conditional check based on the version? Then maybe we should use valid ranges in the filenames test.ge0le22.h5. Otherwise, we would need to generate a file/dir for all the versions.

**Comment by byrnHDF** [comment]
That sounds like a possibility, I need to run through all the combos I can to determine the extent. I am thinking there will only be one branch point (which is 1.8.22 for 1.8) in each branch. Just a handful of files maybe.

**Comment by byrnHDF** [comment]
I think I have tested the different combinations that should cover the various library versions and API selections - for CMake.
Next is to update the autotools.

**Comment by byrnHDF** [comment]
The only tests needing special handling is the nbit test in H5D and the ref tests in H5T.

**Pull request merged**
