### PR TITLE
Complete rework of examples (#7)

### PR DESCRIPTION
**Pull request by brtnfld**
* added search for h5p* wrappers for parallel HDF5 builds to Autotools
* added new example that uses tokens for H5Oinfo
* added workflows
* removed unused directories
* removed duplicate code, now only one set of examples code.

### CODE REVIEW

**Comment by byrnHDF** [comment]
First the examples subdir needs to be eliminated as there is no longer multiple versions. The root config and CMakelists.txt shouldn't be needed.
I will try that locally first.

**Comment by byrnHDF** [comment]
I see one problem - PR #6 did not get merged - that removed unused CMake code.

**Comment by brtnfld** [comment]
@lrknox can you revert that PR for now, it generates a lot of conflicts.

**Comment by brtnfld** [comment]
> I see one problem - PR #6 did not get merged - that removed unused CMake code.

That is unfortunate, if it means anything, I just basically copied the CMake-related files from 1_14 as is. I only had to make minor changes to the test reference locations.

**Comment by byrnHDF** [comment]
> @lrknox can you revert that PR for now, it generates a lot of conflicts.

Oh yeah it would. But it needs to go in before your merge because all the existing tarballs use it. Idon't want to lose those changes.

**Comment by byrnHDF** [comment]
I just tested and that extra level of the examples dir needs to be removed because the root level CMake stuff will be wrong.

**Comment by brtnfld** [comment]
I don't understand; why can't we have all the examples in their own directory? We used to have them all in 1_* directories. It helps to isolate them for the top-level fluff.

**Comment by byrnHDF** [comment]
> I don't understand; why can't we have all the examples in their own directory? We used to have them all in 1_* directories. It helps to isolate them for the top-level fluff.

That's my point, there should not be an extra level - the CMake files in root are unnecessary and causes confusion (possible errors) as the root CMake files were specially crafted for the subdirectories of examples. We only want one set of CMake files.

Let me work on it this weekend when I have more time - I need to do something else right now.

**Comment by byrnHDF** [comment]
I have a new version following what you did about 80% finished. Will create a PR once I get it tested.

**Comment by brtnfld** [comment]
Superseded by PR #9

**Pull request closed without merging**
