### PR TITLE
Master new rework

### PR DESCRIPTION
**Pull request by byrnHDF**
This follows #7 mostly, eliminates extra folder.
Some test issues still need attention, but builds for different branches.

### CODE REVIEW

**Comment by brtnfld** [comment]
It looks like this is missing a lot of work from PR#8, what branch was this PR based on?

**Comment by byrnHDF** [comment]
> It looks like this is missing a lot of work from PR#8, what branch was this PR based on?

This is the master branch with the PR #6 merged (which had significant changes)
All the CMake combinations are tested and working: develop, 110, 18 and develop with USE_APIs 112,110,18 and 112 with USE_APIs 110,18.
Still need to test 110 and 18.
Still need to fix the autotools files.

**Comment by byrnHDF** [comment]
CMake builds are working, all combinations.
Will now work on autotools changes.

**Review by brtnfld — APPROVED** [review]

**Comment by brtnfld** [comment]
@byrnHDF can you merge this so I can work on fixing autotools?

**Pull request merged**
